name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: test
      run: |
        pip install poetry
        poetry install
        poetry run poe autoinstall-torch-cuda
        poetry run pre-commit run -a
        poetry run pytest --cov
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
